# Generated by Django 4.1.7 on 2023-03-07 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0003_quiztakers_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='definition',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='definition',
            new_name='test',
        ),
        migrations.AlterField(
            model_name='quiztakers',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takers', to='Account.test'),
        ),
        migrations.AlterField(
            model_name='quiztakers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiztakers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Account.answer'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Account.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='quiztaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Account.quiztakers'),
        ),
    ]
